name: Deploy to CDN Repo
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    if: github.repository == 'freeCodeCamp/testable-projects-fcc'
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: |
          npm install -g yarn

      - name: Get yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77 # tag=v3
        # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build bundle.js and Projects
        run: |
          yarn build

      - name: Deploy
        env:
          CDN_REPO_USER: ${{ secrets.CDN_REPO_USER }}
          CDN_REPO_PASSWORD: ${{ secrets.CDN_REPO_PASSWORD }}
          CDN_REPO_SLUG: ${{ secrets.CDN_REPO_SLUG }}
        run: |
          if [ -n "$CDN_REPO_PASSWORD" ] && \
            git log -1 --name-only -m --pretty='format:' | grep -q '^src/'
          then
            git clone https://github.com/"$CDN_REPO_SLUG"

            # Copy build files to local CDN repo
            cp -r --parents build/testable-projects-fcc/* cdn/

            # Check for changes and push them to CDN repo
            cd cdn/

            if [ -n "$(git status --porcelain)" ]
            then
              git add .
              git -c user.name="$CDN_REPO_USER" -c user.email='camperbot@users.noreply.github.com' \
                commit -m 'chore(release): update testable-projects-fcc bundle on cdn'
              git push https://"$CDN_REPO_USER":"$CDN_REPO_PASSWORD"@github.com/"$CDN_REPO_SLUG" main
            fi
          fi
