name: Deploy to CDN Repo
on:
  workflow_dispatch:
  schedule:
    - cron: '25 0/12 * * 1-5' # Build once every 12 hours, starting at 25 minutes past the hour (UTC)

jobs:
  deploy:
    name: Deploy
    if: github.repository == 'freeCodeCamp/testable-projects-fcc'
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: |
          npm install -g yarn

      - name: Get yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build bundle.js and Projects
        run: |
          yarn build

      - name: Checkout CDN Repo Source
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
        with:
          repository: 'freeCodeCamp/cdn'
          token: ${{ secrets.CDN_REPO_USER_PAT }}
          path: cdn
      
      - name: Copy bundle.js and Projects
        run: |
          cp -r --parents build/testable-projects-fcc/* cdn/

      - name: Create a Pull Request to CDN Repo
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4
        id: cpr
        with:
          token: ${{ secrets.CDN_REPO_USER_PAT }}
          commit-message: 'chore: update testable-projects-fcc'
          committer: campebot <campebot@users.noreply.github.com>
          author: campebot <campebot@users.noreply.github.com>
          title: 'chore: update testable-projects-fcc'
          body: 'This PR was automatically generated by a GitHub Action. If you have any questions or concerns, please contact `@freeCodeCamp/dev-team`.'
          branch: 'chore/update-testable-projects-fcc'
          path: cdn
          delete-branch: true

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@684fed02ccc9b5eefcf7d40b65b3cd44255bd5bc # v2
        with:
          token: ${{ secrets.CDN_REPO_USER_PAT }}
          repository: 'freeCodeCamp/cdn'
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
      
      - name: Auto approve
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: juliangruber/approve-pull-request-action@6b8b2f82d50cea1e4329bcdfe940a6ceccbe528e # v2
        with:
          github-token: ${{ secrets.CDN_REPO_USER_PAT }}
          repo: 'freeCodeCamp/cdn'
          number: ${{ steps.cpr.outputs.pull-request-number }}
