name: Node.js CI
on: [push, pull_request]

jobs:
  selenium-tests:
    name: Selenium Tests
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: |
          npm install -g yarn

      - name: Get yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build bundle.js and Projects
        run: |
          # Build bundle.js and projects
          yarn build

      - name: Update apt Repository
        run: |
          sudo apt update

      - name: Test Chrome
        env:
          SELENIUM_BROWSER: chrome
          BROWSER_PATH: /usr/bin/google-chrome-stable
          DETECT_CHROMEDRIVER_VERSION: true
          SCREENSHOT_DIR: travis-screenshots
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome*.deb

          yarn test

      - name: Test Firefox
        env:
          SELENIUM_BROWSER: firefox
          BROWSER_PATH: firefox
          SCREENSHOT_DIR: travis-screenshots
        run: |
          sudo apt install -y firefox

          yarn test
